### ISSUE TITLE
Dataloader unnecessary in simple DNN_dataset.py function process_jets

### ISSUE THREAD

**Issue by nseeba** [HEP-KBFI/ml-tau-en-reg#11]
https://github.com/HEP-KBFI/ml-tau-en-reg/blob/1de2af92c40320b1b0d7306c6075e37d04437580/enreg/tools/data_management/simpleDNN_dataset.py#L142-L149

The dataloader part here seems to be unnecessary.

**Comment by jpata** [comment]
Fixed here: https://github.com/HEP-KBFI/ml-tau-en-reg/commit/19ffcd99b82dee9faccae60d5b55ec8b44a9554f#diff-95355f27a76734afe03d7d8db812ea1d6c5b29e437ee0bdf52e0ebe12aa8391fR146
