### ISSUE TITLE
Ablations with different feature sets

### ISSUE THREAD

**Issue by jpata** [HEP-KBFI/ml-tau-en-reg#17]
First need to fix https://github.com/HEP-KBFI/ml-tau-en-reg/issues/16 and https://github.com/HEP-KBFI/ml-tau-en-reg/issues/20.

Then do the following ablations:
- LN, PT, SDNN with only kinematics
- LN, PT, SDNN with kinematics + additional 13 features (pdgs, dEta, dPhi etc)
- LN, PT, SDNN with kinematics + additional 13 features + additional lifetime variables

**Comment by Laurits7** [comment]
Addressed in #66
