### ISSUE TITLE
make training features configurable

### ISSUE THREAD

**Issue by jpata** [HEP-KBFI/ml-tau-en-reg#20]
For all 3 models, both `input_dim` of each model and the `unpack_...` functions (https://github.com/HEP-KBFI/ml-tau-en-reg/blob/main/enreg/scripts/trainModel.py#L46-L71) need to take into account three possible feature sets:
- only kinematics
- kinematics + additional features like PDGs
- kinematics + additional features + lifetimes

This should be easily configurable with a single flag (e.g. `feature_set=[kinematics]`, `feature_set=[kinematics,pdgs]`, `feature_set=[kinematics,pdgs,lifetimes]`, to enable scanning across the options in https://github.com/HEP-KBFI/ml-tau-en-reg/issues/17.

**Comment by jpata** [comment]
possible next task for @HardiVv.

**Comment by HardiVv** [comment]
This has been adressed in issue #62

**Comment by jpata** [comment]
Done for all models in #65.
