### ISSUE TITLE
split regression figures, increase font size

### ISSUE THREAD

**Issue by jpata** [HEP-KBFI/ml-tau-en-reg#33]
Split the regression figures to separate PDFs, increase the font sizes so they are readable without zooming.

<img width="606" alt="Screenshot 2024-06-17 at 12 02 11" src="https://github.com/HEP-KBFI/ml-tau-en-reg/assets/69717/e0f7b59a-68c3-4a44-958b-7a010fb9a048">

**Comment by Laurits7** [comment]
Done in PR #36
