### ISSUE TITLE
PDG mismatch with sim data

### ISSUE THREAD

**Issue by HardiVv** [HEP-KBFI/ml-tau-en-reg#35]
First this is the way I remapped the DMs
```
remap_d = 
{0: '$h^\pm$', # DM0 
1: '$h^\pm \pi^0$', # DM1
2: '$h^\pm \geq 2\pi^0$', # DM2, DM3, DM4
3: '$h^\pm h^\mp h^\pm$', # DM10
4: '$h^\pm h^\mp h^\pm \geq \pi^0$', # DM11, DM12
5: 'Other'} # DM15 and others 5-9
```
I used the values from: [pdg website](https://pdglive.lbl.gov/Particle.action?node=S035&init=0)
`PDG_vals = [11.51, 25.93, 10.81, 9.8, 5.29, 1.45]`

calculated the 'other' like this 
```
100 - 17.39 -17.82 - x - 11.51 - 25.93 - 10.81 - 9.8 - 5.29 = 0
x = 1.45
```

Then used a simple cross-multiplication where $\tau_h = 64.79 → 100$ for PDG, and sim data to get the ratios
```
z_ratios [0.1409, 0.4081, 0.1956, 0.1629, 0.091, 0.0015]
zh_ratios [0.1431, 0.4083, 0.1936, 0.1629, 0.0906, 0.0015]
PDG_ratios [0.1777, 0.4002, 0.1668, 0.1513, 0.0816, 0.0224]
```

then I half-assed the errors as well to get this result:
![image](https://github.com/HEP-KBFI/ml-tau-en-reg/assets/157815763/bc14c717-a07f-4ed4-93f9-66b8d5a4d9b9)

Even with the errors, the sim dosen't fit well with PDG

Maybe we should check raw simulation files before ntuplizer.

**Comment by Laurits7** [comment]
So I did some digging. As per PYTHIA 8.3 documentation [1], the rare decay modes (except for the {gamma+pi0+pi^-} and some that include eta that allow 5-prong) are not simulated as shown in the following table.
![image](https://github.com/HEP-KBFI/ml-tau-en-reg/assets/30724920/3ba9ac42-6c9b-4b96-9733-94d5ac38c986)
Furthermore, the decay mode including photon was not classified as a rare decay mode - changing this little bit, the decay mode fractions are the following:
![image](https://github.com/HEP-KBFI/ml-tau-en-reg/assets/30724920/318d6372-aeb4-45a7-9294-b34d2fa16886)


[1] https://www.pythia.org/pdfdoc/pythia8300.pdf [page 196, Table 3]

**Comment by jpata** [comment]
Simulated fraction of one-prong (DM0) is the SAME in .hepmc and PDG.
Therefore, the difference in DM0 between .root and PDG is probably due to selection effects from jet clustering min pt.

**Comment by Laurits7** [comment]
Indeed, the difference comes from the different kinematics of the decay modes and the pt threshold (of 20 GeV) of the jet clustering:

![dm_plot](https://github.com/HEP-KBFI/ml-tau-en-reg/assets/30724920/77d4636a-5a01-4f14-bc89-ae5715266979)
