### ISSUE TITLE
Use comet.ml logging

### ISSUE THREAD

**Issue by jpata** [HEP-KBFI/ml-tau-en-reg#58]
Log losses, script versions and system metrics from the training into comet, like I'm doing here: https://www.comet.com/jpata/particleflow-pt/view/new/panels

https://github.com/jpata/particleflow/blob/98d59c2c7da31d760fb6c55ba53d9f951cc28890/mlpf/pyg_pipeline.py#L13

**Comment by Laurits7** [comment]
Addressed in #76
