### ISSUE TITLE
OmniJet for Embed in ParticleTransformer

### ISSUE THREAD

**Issue by jpata** [HEP-KBFI/ml-tau-en-reg#68]
use OmniJet tokenizer + GPT backbone for the per-particle embedding in ParticleTransformer.

**Comment by Laurits7** [comment]
One version is addressed in #69. The two other implementations not done so far are the

- OmniJetBB encoding + ParT features (256+13)
- OmnijetBB encoding + ParT features embedding (256+256)

**Comment by Laurits7** [comment]
v2.1 and v2.2 addressed in PR #70

**Comment by Laurits7** [comment]
In PR #75 both the ParT embedding and self-attention layers were replaced by the OmniJet backbone embedding for a simpler model.
